### PR TITLE
fix: added missing dep chart.js (required for react-chartjs-2)

### PR DESCRIPTION
**Pull request by davidediak**

### CODE REVIEW

**Comment by theodubiel** [comment]
@photonized The good sir here is correct.

https://www.npmjs.com/package/react-chartjs-2

Docs state this is needed.  Odd that it still works?  

@davidediak Any idea why it still functions normally without?  Or did we just not use a feature which depends on the dep.

**Comment by vladjdk** [comment]
Can you remove your package-lock.json and include that file in the .gitignore?

**Comment by davidediak** [comment]
> @davidediak Any idea why it still functions normally without? Or did we just not use a feature which depends on the dep.

My guess is you installed it locally, then removed it from the package before committing thinking it was unnecessary. 
FE doesn't compile without that dep.

> Can you remove your package-lock.json and include that file in the .gitignore?

Not a good idea, package-lock.json should always be versioned.

**Comment by theodubiel** [comment]
Thanks @davidediak for pointing this out!  We are going to close this PR as I pulled in the missing package when I added thee latest chart.

**Pull request closed without merging**
